spring:
  config:
    activate:
      on-profile: default

wiremock:
  server:
    port: 8090
    fileSourcePath: src/main/resources
    verbose: true
    asynchronousResponseEnabled: true
    asynchronousResponseThreads: 20
    jettyAcceptors: 4

logging:
  level:
    ROOT: INFO
    com.epam: DEBUG